# Generated by Django 5.2.5 on 2025-08-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('sport', 'Спорт'), ('politics', 'Политика'), ('education', 'Образование'), ('showbiz', 'Шоубизнес'), ('breaking_news', 'Срочные новости'), ('economy', 'Экономика')], max_length=50, unique=True),
        ),
    ]
